### ISSUE TITLE
Unable to take screenshot in wsl

### ISSUE THREAD

**Issue by MuizU** [JMcKiern/vim-shoot#5]
I am unable to take a screenshot in wsl (windows subsystem for linux) and am getting the following error.

`Error detected while processing function shoot#Shoot[22]..provider#python3#Call:
                                                                                                                     │line   18:
                                                                                                                     │Error invoking 'python_execute' on channel 6 (python3-script-host):
                                                                                                                     │Traceback (most recent call last):
                                                                                                                     │  File "<string>", line 10, in <module>
                                                                                                                     │  File "/home/muizu/.local/share/nvim/plugged/vim-shoot/lib/shoot.py", line 6, in <module>
                                                                                                                     │    import driver_mgr
                                                                                                                     │  File "/home/muizu/.local/share/nvim/plugged/vim-shoot/lib/driver_mgr.py", line 3, in <module>
                                                                                                                     │    from selenium import webdriver
                                                                                                                     │ModuleNotFoundError: No module named 'selenium'`

I am currently using a wsl with arch linux

**Comment by JMcKiern** [comment]
Have you run `install.py`? This should install the dependencies, one of them being selenium.

The [README](https://github.com/JMcKiern/vim-shoot#installation-with-vim-plug) provides instructions on how to do this if using vim-plug.
